# Generated by Django 5.0.3 on 2024-03-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("joystick_jury", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_title",
            field=models.CharField(default="Worse that ET >:(", max_length=200),
            preserve_default=False,
        ),
    ]
