# Generated by Django 5.0.3 on 2024-03-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joystick_jury', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('release_date', models.DateTimeField(verbose_name='date published')),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
